### PR TITLE
Update to the latest version

### PR DESCRIPTION
**Pull request by paulomorgado**
Update download link to the latest version.

### CODE REVIEW

**Comment by brianrob** [comment]
@sharwell that's a great idea.  @paulomorgado do you want to change this to use an auto-updating badge?

**Comment by paulomorgado** [comment]
Sure, @microsoft.

Is that what you posted, @sharwell?

Or is it more like this?

    [GitHub release (latest SemVer)](https://github.com/microsoft/perfview/releases/download/P2.0.46/PerfView.exe)

Still needs a manual change for the download link.

Maybe this would be enough:

    [GitHub release (latest SemVer)](https://github.com/microsoft/perfview/releases/latest)
[GitHub release (latest SemVer)](https://github.com/microsoft/perfview/releases/latest)

It points to the page of the latest release.

**Comment by brianrob** [comment]
@paulomorgado, lets use the latter.  That way, when we add new releases, this doesn't have to be modified.  I always forget.  :)

**Comment by paulomorgado** [comment]
Done!

**Pull request merged**
