### PR TITLE
Toggle column visiblity in PerfDataGrid

### PR DESCRIPTION
**Pull request by WardenGnaw**
Ability to select columns in a view. This is so that you can have more space for columns you are actively interested in. You can save the column view preferences. 

image

### CODE REVIEW

**Comment by vancem** [comment]
I am wondering if this is the best user experience.     I would have expected it to be the case that I would want to choose columns for EVERY view at once (not to have to change them one at a time for each view.    The list would be the union of the column names over all views.  

Do you really think there is value in having different settings for each view?

**Comment by WardenGnaw** [comment]
That seems like a better user experience to have consistent column view settings across all the PerfGridViews. I'll change it to do that.

**Comment by WardenGnaw** [comment]
@vancem When you have the time, could you look at my changes? 

Thanks!

**Comment by vancem** [comment]
Looks Good To Me.     Thanks for your contribution.

**Pull request merged**
