### PR TITLE
Convert C++ projects to VS2022

### PR DESCRIPTION
**Pull request by paulomorgado**

### CODE REVIEW

**Comment by brianrob** [comment]
@paulomorgado, can you please update .ado.yml to use `windows-2022` images?  This will install VS 2022, which is required by your change.

**Comment by paulomorgado** [comment]
@brianrob, done!

**Comment by pharring** [comment]
I'm totally in favor of making VS 2022 the required development environment. We should update this section of the README:
https://github.com/microsoft/perfview#tools-needed-to-build-perfview

**Comment by paulomorgado** [comment]
@pharring, done!

I changed "VS" to "Visual Studio" to make it easy to change next time.

**Review by brianrob — APPROVED** [review]
LGTM.  Thanks @paulomorgado.  I will get this merged soon - I'm working on an issue with the CI and I want to get that addressed first before merging this.

**Comment by paulomorgado** [comment]
@brianrob, these solution item references don't exist:

[appveyor.yml](https://github.com/microsoft/perfview/blob/8316a3820e3eec57317c0ddf1b50bff79bf9fc5e/PerfView.sln#L36)
[.nuget\packages.config](https://github.com/microsoft/perfview/blob/8316a3820e3eec57317c0ddf1b50bff79bf9fc5e/PerfView.sln#L40)

Do you want me to clean that up as part of this PR?

**Comment by brianrob** [comment]
Let's do that in a separate PR please.

**Pull request merged**
