### PR TITLE
Fix race conditions due to static state in ComputerNameExists

### PR DESCRIPTION
**Pull request by sharwell**

### CODE REVIEW

**Comment by vancem** [comment]
I don't really like the idea of a cache at all because the value of this could change over time.   

A review of the callers, shows that the caching is not necessary (they are all write-once locations).   

My recommendation is to rip the caching out completely.

**Comment by sharwell** [comment]
Works for me; updated to remove the caching altogether.

**Comment by vancem** [comment]
LGTM.  I want to do one or two scenarios two to confirm we don't get big delays because of this.

**Comment by sharwell** [comment]
@vancem Thanks. I would recommend testing the worst case by locally forcing the timeout as follows:

```csharp
Thread.Sleep(timeout);
return false;
```

**Comment by vancem** [comment]
LGTM

**Pull request merged**
