### PR TITLE
Added horizontal scroll for perfgrids

### PR DESCRIPTION
**Pull request by ilabutin**
As an attempt to make better solution for #300 I've implemented horizontal scrolling within first column of the grid.
The scrollbar appears below grid when necessary.

Works fine for me, but should be tested better on larger dumps to check performance.

It is better to use see diff ignoring whitespace differences: https://github.com/Microsoft/perfview/pull/592/files?w=1

### CODE REVIEW

**Comment by ilabutin** [comment]
It is better to use see diff ignoring whitespace differences: https://github.com/Microsoft/perfview/pull/592/files?w=1

**Comment by ilabutin** [comment]
@vancem @adamsitnik 
Any chance to also look at this one? I have this running in my local build and didn't experience any issues so far..

**Comment by vancem** [comment]
This one will take a little longer to review properly, but I should be able to do it this week.

Vance

**Comment by ilabutin** [comment]
I'm closing this and will create new one.

**Pull request closed without merging**
