### PR TITLE
Prune GCBulkMovedObjectRanges from the ETLX

### PR DESCRIPTION
**Pull request by sharwell**
This event is large, but unused. Removing it allows for a substantial increase in the amount of GC allocation data that can be analyzed in one trace.

### CODE REVIEW

**Comment by brianrob** [comment]
@sharwell, I don't think that we should remove this event from the resulting etlx.  The general pattern here is that any event whose data is captured in the resulting TraceLog side tables during creation can then be removed.  This rationale for this pattern is that many of these events are rundown events that might be present later in the trace but needed for analysis of earlier events.  The GCBulkMovedObjectRanges event is not encapsulated in the resulting TraceLog and is needed at processing time by any tools that might keep track of the heap state of the process.

**Comment by sharwell** [comment]
I may have understated the impact of this event. This event is 75+% of the resulting ETLX, while the GC events are _much_ smaller. By omitting this event, I can analyze ~10x the GC data I would otherwise be able to.

**Comment by sharwell** [comment]
Another option is finding a way to exclude this event from the "GC Only" scenario.

**Comment by brianrob** [comment]
When you collect with /GCOnly, what type of analysis are you doing?  For most GC analysis, we recommend /GCCollectOnly which only tells you about collections and should not contain heap information events such as GCBulkMovedObjectRanges.

**Comment by sharwell** [comment]
I'm using GC Heap Alloc Ignore Free for scenarios that allocate 200-500GiB.

**Comment by brianrob** [comment]
Are you using sampled allocations, or are you using the profiler API based .NET Alloc support?

**Comment by sharwell** [comment]
I'm using whatever the default options are for the "GC Only" check box.

**Comment by sharwell** [comment]
image

**Comment by brianrob** [comment]
Right, what I mean is which of the views are you using?  I suspect that there is a configuration you can use to get what you want.

**Comment by sharwell** [comment]
I use **GCStats** and **GC Heap Alloc Ignore Free (Coarse Sampling) Stacks**

**Comment by sharwell** [comment]
@VSadov are you able to help with this one?

**Comment by VSadov** [comment]
I am not sure I will have time to look at this in the next few days, but filtering out collected events seems unusual.
CC @Maoni0

**Comment by sharwell** [comment]
@VSadov equally acceptable would be an easier way to prevent this costly but unused event from getting collected.

**Comment by Maoni0** [comment]
> This event is large, but unused.

this event is used to construct heap graphs. 

if you want to prevent it from being collected for the /GCOnly commandline, then yes I'd agree with that (in fact I've advocated this before but since very few people actually use the /GCOnly cmdline we never actually did anything). but if you mean someone already collected them in the .etl and you want to get rid of them when we write out the .etlx that doesn't seem reasonable 'cause obviously you can use them and if someone intentionally collected them they should keep them.

**Comment by sharwell** [comment]
@Maoni0 yes, as soon as I know how to update `/GCOnly` to avoid this event, I will update this pull request to implement it that way. The problem is I don't know how/why this event is being enabled.

**Comment by Maoni0** [comment]
this event is under the `GCHeapSurvivalAndMovement` keyword; please see https://github.com/microsoft/perfview/blob/master/src/PerfView/CommandLineArgs.cs#L446

**Comment by sharwell** [comment]
Awesome! Are there any other events enabled by that keyword that I wouldn't want to remove?

**Comment by sharwell** [comment]
Also @Maoni0, I'd like to turn this off for the default thread time and CPU sampling scenarios, in addition to /GCOnly. Obviously the event would be enabled for /GCCollectOnly. This leaves the following questions:

1. Do we need an easy way to turn this event back on for scenarios other than /GCCollectOnly?
2. If the answer is 'yes', which check box would it be tied to? My guesses are:
    1. The existing **.NET Alloc** check box, which is not checked by default
    2. A new check box, possibly called **GC Heap**

**Comment by Maoni0** [comment]
> Obviously the event would be enabled for /GCCollectOnly.

typo? would NOT be enabled for /GCCollectOnly.

I think the bulk move event should only be enabled for options that actually make used of them. and I'm unfamiliar which options in the UI do that. @brianrob would know more.

**Comment by sharwell** [comment]
I found a different way to achieve this goal

**Pull request closed without merging**
