### PR TITLE
Reproduce vstest issue

### PR DESCRIPTION
**Pull request by nohwnd**
Reverting back the version of vstest to get another build that fails to produce TRX so I can debug this.

### CODE REVIEW

**Comment by nohwnd** [comment]
@brianrob I don't fully understand why 17.6.2 works and 17.7+ does not, but both builds have the same problem. The tests don't finish, and you exit vstest.console with 0 exit code, which makes the runner think everything is okay, but instead you finished just half of your tests. 

I can see the same locally, where running PerfViewTests will show perfview window and then it will exit. In the test output you can see that the last test is passed, but there is no summary. 

Linux tracing tests ✔️:
image

PerfView tests ❌:

image


`TestSetTimeRangeInStartTextBoxRuRu02Async` test comes up in Blame, and ends up exiting the process here:
https://github.com/microsoft/perfview/blob/main/src/PerfView/MainWindow.xaml.cs#L2058

```
 	mscorlib.dll!System.Environment.Exit(int exitCode) Line 725	C#
 	PerfView.exe!PerfView.MainWindow.Window_Closed(object sender, System.EventArgs e) Line 2058	C#
 	PresentationFramework.dll!System.Windows.Window.OnClosed(System.EventArgs e)	Unknown
 	PresentationFramework.dll!System.Windows.Window.WmDestroy()	Unknown
 	PresentationFramework.dll!System.Windows.Window.WindowFilterMessage(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled)	Unknown
 	PresentationCore.dll!System.Windows.Interop.HwndSource.PublicHooksFilterMessage(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled) Line 1309	C#
 	WindowsBase.dll!MS.Win32.HwndWrapper.WndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam, ref bool handled) Line 221	C#
 	WindowsBase.dll!MS.Win32.HwndSubclass.DispatcherCallbackOperation(object o) Line 253	C#
 	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate callback, object args, int numArgs) Line 73	C#
>	WindowsBase.dll!System.Windows.Threading.ExceptionWrapper.TryCatchWhen(object source, System.Delegate callback, object args, int numArgs, System.Delegate catchHandler) Line 24	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.WrappedInvoke(System.Delegate callback, object args, int numArgs, System.Delegate catchHandler) Line 1740	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority priority, System.TimeSpan timeout, System.Delegate method, object args, int numArgs) Line 954	C#
 	WindowsBase.dll!System.Windows.Threading.Dispatcher.Invoke(System.Windows.Threading.DispatcherPriority priority, System.Delegate method, object arg) Line 814	C#
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam) Line 207	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	WindowsBase.dll!MS.Win32.HwndSubclass.DefWndProcWrapper(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam) Line 318	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	WindowsBase.dll!MS.Win32.HwndSubclass.CallOldWindowProc(System.IntPtr oldWndProc, System.IntPtr hwnd, MS.Internal.Interop.WindowMessage msg, System.IntPtr wParam, System.IntPtr lParam) Line 261	C#
 	WindowsBase.dll!MS.Win32.HwndSubclass.SubclassWndProc(System.IntPtr hwnd, int msg, System.IntPtr wParam, System.IntPtr lParam) Line 225	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	PresentationFramework.dll!System.Windows.Window.InternalClose(bool shutdown, bool ignoreCancel)	Unknown
 	PresentationFramework.dll!System.Windows.Window.Close()	Unknown
 	PerfViewTests.dll!PerfViewTests.Utilities.PerfViewTestBase.Dispose(bool disposing) Line 104	C#
 	PerfViewTests.dll!PerfViewTests.Utilities.PerfViewTestBase.Dispose() Line 94	C#
 	xunit.execution.desktop.dll!Xunit.Sdk.ExecutionTimer.Aggregate(System.Action action) Line 32	C#
 	xunit.execution.desktop.dll!ReflectionAbstractionExtensions.DisposeTestClass(Xunit.Abstractions.ITest test, object testClass, Xunit.Sdk.IMessageBus messageBus, Xunit.Sdk.ExecutionTimer timer, System.Threading.CancellationTokenSource cancellationTokenSource) Line 80	C#
 	Xunit.StaFact.dll!Xunit.Sdk.UITestInvoker.RunAsync.AnonymousMethod__2()	Unknown
 	xunit.core.dll!Xunit.Sdk.ExceptionAggregator.Run(System.Action code) Line 74	C#
 	Xunit.StaFact.dll!Xunit.Sdk.UITestInvoker.RunAsync.AnonymousMethod__1()	Unknown
 	xunit.core.dll!Xunit.Sdk.ExceptionAggregator.Run(System.Action code) Line 74	C#
 	Xunit.StaFact.dll!Xunit.Sdk.UITestInvoker.RunAsync.AnonymousMethod__2_0()	Unknown
 	Xunit.StaFact.dll!Xunit.Sdk.UITestInvoker.RunOnSTA.AnonymousMethod__0()	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 516	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx) Line 488	C#
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state) Line 481	C#
 	mscorlib.dll!System.Threading.ThreadHelper.ThreadStart() Line 69	C#
 	[Native to Managed Transition]	
```

**Comment by nohwnd** [comment]
@dogirala Please have a look on the most recent build. We can see it consistently fail with TP 17.6 but not with 17.7 and newer. In both cases the run exits prematurely, because the tested app exits with exit code 0. (You can see there is no summary of the test run.) In both cases there is no TRX file, and in both cases the results directory is also not there. 

But still the Publishing TRX finishes without an error with TP 17.6, and with error with TP 17.7. The errors are coming from the ADO task, and not TP. Are you aware of any condition on the version of TP that might cause this? 


Logs frothe run are below, in case it gets removed: 

The failed run (17.7):
```
2023-10-05T13:10:09.4704832Z **************** Completed test execution *********************
2023-10-05T13:10:09.4705966Z ##[debug]Current Phase: MS.VS.TestService.VstestConsoleAdapter.ExecuteVsTestPhase Phase Result: MS.VS.TestService.VstestConsoleAdapter.ExecutionVsTestPhaseResults
2023-10-05T13:10:09.4707005Z ##[debug]PERF WARNING: Running the phase MS.VS.TestService.VstestConsoleAdapter.ExecuteVsTestPhase: took 24762.4217 ms
2023-10-05T13:10:09.4708093Z ##[debug]Current phase: MS.VS.TestService.VstestConsoleAdapter.PublishTestResultPhase
2023-10-05T13:10:09.4756540Z ##[debug]Starting Publish Test Results: TIA: False
2023-10-05T13:10:10.5544825Z ##[debug]Starting PublishTestResult from Result Files
2023-10-05T13:10:11.5712431Z ##[debug]Test results directory not found. Check if your test binaries have tests. <<<<<<<<<<<<<<<
2023-10-05T13:10:11.5716570Z Test results files:  <<<<<<<<
2023-10-05T13:10:11.5717840Z ##[debug]PERF: PublishTestResultPhase.Publish: took 4.4585 ms
2023-10-05T13:10:11.5718595Z ##[debug]Completed Publish Test Results.
2023-10-05T13:10:11.5719207Z ##[debug]Current Phase: MS.VS.TestService.VstestConsoleAdapter.PublishTestResultPhase Phase Result: MS.VS.TestService.VstestConsoleAdapter.PublishTestResultPhaseResults
2023-10-05T13:10:11.5720231Z ##[error]Error occurred while publishing test results : MS.VS.TestService.VstestConsoleAdapter.NoTrxFoundException: No trx files found in the specified test results directory D:\a\_temp\TestResults. <<<<<<<<<<<<<<<<<
2023-10-05T13:10:11.5721346Z ##[debug]Processed: ##vso[task.logissue type=error;]Error occurred while publishing test results : MS.VS.TestService.VstestConsoleAdapter.NoTrxFoundException: No trx files found in the specified test results directory D:\a\_temp\TestResults.  <<<<<<<<<<<<<<<<<<<<
2023-10-05T13:10:11.5722085Z ##[debug]PERF: Running the phase MS.VS.TestService.VstestConsoleAdapter.PublishTestResultPhase: took 10.6215 ms
2023-10-05T13:10:11.5722764Z ##[debug]Current phase: MS.VS.TestService.VstestConsoleAdapter.TestRunCompletionPhase
2023-10-05T13:10:11.5723353Z ##[debug]Started TestRunCompletionPhase 0
2023-10-05T13:10:11.5723921Z ##[error]Skipping marking test run as complete as test run id 0 is invalid.
2023-10-05T13:10:11.5724502Z ##[debug]Processed: ##vso[task.logissue type=error;]Skipping marking test run as complete as test run id 0 is invalid.
2023-10-05T13:10:11.5725399Z ##[debug]Current Phase: MS.VS.TestService.VstestConsoleAdapter.TestRunCompletionPhase Phase Result: MS.VS.TestService.VstestConsoleAdapter.TestRunCompletionPhaseResults
2023-10-05T13:10:11.5726211Z ##[debug]PERF: Running the phase MS.VS.TestService.VstestConsoleAdapter.TestRunCompletionPhase: took 3.3105 ms
2023-10-05T13:10:11.5726903Z ##[debug]Current phase: MS.VS.TestService.VstestConsoleAdapter.CleanupPhase
2023-10-05T13:10:11.5727519Z ##[debug]Started CleanupPhase 0
2023-10-05T13:10:11.5728172Z ##[debug]Looking for diag files with pattern Attempt*zpqwjt*.diag
2023-10-05T13:10:11.5740338Z ##[debug]Processed: ##vso[task.uploadfile]D:\a\_temp\Attempt--1_zpqwjt.diag
2023-10-05T13:10:11.5741253Z ##[debug]Completed CleanupPhase 0
2023-10-05T13:10:11.5741871Z ##[debug]Current Phase: MS.VS.TestService.VstestConsoleAdapter.CleanupPhase Phase Result: MS.VS.TestService.VstestConsoleAdapter.CleanupPhaseResults
2023-10-05T13:10:11.5742513Z ##[debug]PERF: Running the phase MS.VS.TestService.VstestConsoleAdapter.CleanupPhase: took 141.9836 ms
2023-10-05T13:10:11.5743088Z ##[debug]Completed the ExecutionStateModel
2023-10-05T13:10:11.5743417Z Completed TestExecution Model...
2023-10-05T13:10:11.5743895Z ##[debug]Exit code 1 received from tool 'D:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.227.0\Modules\DTAExecutionHost.exe'
2023-10-05T13:10:11.5744546Z ##[debug]STDIO streams have closed for tool 'D:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.227.0\Modules\DTAExecutionHost.exe'
2023-10-05T13:10:11.5745286Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2023-10-05T13:10:11.5747247Z ##[debug]Processed: ##vso[task.issue type=warning;]Vstest failed with error. Check logs for failures. There might be failed tests.
2023-10-05T13:10:11.5748556Z ##[error]Error: The process 'D:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.227.0\Modules\DTAExecutionHost.exe' failed with exit code 1
2023-10-05T13:10:11.5749751Z ##[debug]Processed: ##vso[task.issue type=error;]Error: The process 'D:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.227.0\Modules\DTAExecutionHost.exe' failed with exit code 1
2023-10-05T13:10:11.5750829Z ##[debug]DtaExecutionHost finished
2023-10-05T13:10:11.5751378Z ##[debug]Modules/DTAExecutionHost.exe process exited with code 1
2023-10-05T13:10:11.5754173Z ##[debug]task result: Failed
2023-10-05T13:10:11.5755175Z ##[error]Vstest failed with error. Check logs for failures. There might be failed tests.
2023-10-05T13:10:11.5755872Z ##[debug]Processed: ##vso[task.issue type=error;]Vstest failed with error. Check logs for failures. There might be failed tests.
2023-10-05T13:10:11.5759896Z ##[debug]Processed: ##vso[task.complete result=Failed;done=true;]Vstest failed with error. Check logs for failures. There might be failed tests.
2023-10-05T13:10:11.5762196Z ##[section]Finishing: Run Tests
```

Passing run (17.6): 

```
##[debug]Exited vstest.console.exe with code 0.
##[debug]PERF: ExecuteVsTestPhase.InvokeVSTest: took 22435.9555 ms
Vstest.console.exe exited with code 0.
**************** Completed test execution *********************
##[debug]Current Phase: MS.VS.TestService.VstestConsoleAdapter.ExecuteVsTestPhase Phase Result: MS.VS.TestService.VstestConsoleAdapter.ExecutionVsTestPhaseResults
##[debug]PERF WARNING: Running the phase MS.VS.TestService.VstestConsoleAdapter.ExecuteVsTestPhase: took 22437.8373 ms
##[debug]Current phase: MS.VS.TestService.VstestConsoleAdapter.PublishTestResultPhase
##[debug]Starting Publish Test Results: TIA: False
##[debug]Starting PublishTestResult from Result Files
##[debug]Test results directory not found. Check if your test binaries have tests. <<<<<<<<<<<<<<<<<<<<<
Test results files: 
##[debug]PERF: PublishTestResultPhase.Publish: took 4.0182 ms
##[debug]Completed Publish Test Results.
##[debug]Current Phase: MS.VS.TestService.VstestConsoleAdapter.PublishTestResultPhase Phase Result: MS.VS.TestService.VstestConsoleAdapter.PublishTestResultPhaseResults
##[debug]PERF: Running the phase MS.VS.TestService.VstestConsoleAdapter.PublishTestResultPhase: took 9.3979 ms
##[debug]Current phase: MS.VS.TestService.VstestConsoleAdapter.CleanupPhase
##[debug]Started CleanupPhase 0
##[debug]Looking for diag files with pattern Attempt*dr1r4v*.diag
##[debug]Processed: ##vso[task.uploadfile]D:\a\_temp\Attempt--1_dr1r4v.diag
##[debug]Completed CleanupPhase 0
##[debug]Current Phase: MS.VS.TestService.VstestConsoleAdapter.CleanupPhase Phase Result: MS.VS.TestService.VstestConsoleAdapter.CleanupPhaseResults
##[debug]PERF: Running the phase MS.VS.TestService.VstestConsoleAdapter.CleanupPhase: took 208.4186 ms
##[debug]Completed the ExecutionStateModel
Completed TestExecution Model...
##[debug]Exit code 0 received from tool 'D:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.227.0\Modules\DTAExecutionHost.exe'
##[debug]STDIO streams have closed for tool 'D:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.227.0\Modules\DTAExecutionHost.exe'
##[debug]DtaExecutionHost finished
##[debug]Modules/DTAExecutionHost.exe exited with code 0
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;done=true;]Task succeeded
Finishing: Run Tests
```

**Comment by brianrob** [comment]
@nohwnd, confirming this can be closed?

**Comment by nohwnd** [comment]
Yes this PR can be closed. But the issue is not solved, I don't think this is vstest issue, @dogirala please open one on azdo.

**Pull request closed without merging**
