### PR TITLE
Update ClrTraceEventParser with new assembly loader events

### PR DESCRIPTION
**Pull request by elinor-fung**
Update ClrTraceEventParser to properly show new assembly loader events: https://github.com/dotnet/runtime/blob/5da85d0c4b6fc390047cb466a9e0ed674d9c121f/src/coreclr/src/vm/ClrEtwAll.man#L1673-L1808

### CODE REVIEW

**Comment by brianrob** [comment]
@elinor-fung thanks for contributing this.  Do you have a trace file that contains examples of these new events?  I'm interested to see what real data from these events looks like.

**Comment by elinor-fung** [comment]
Trace with a few assembly loads (not actually a .zip - just a .nettrace with the .zip added): [trace-assemblyLoader.nettrace.zip](https://github.com/microsoft/perfview/files/4037132/trace-assemblyLoader.nettrace.zip)

That was from a program that explicitly loads System.Xml by name and then another assembly (AssemblyToLoad) that relies on an event handler to be found.

Short snippet from the events view could be something like:

Event Name                                                         |                 Stage | Result           | AssemblyName                                     | ResultAssemblyPath                                               | Rest                                                                        
--- | --- | --- | --- | --- | ---
Microsoft-Windows-DotNETRuntime/AssemblyLoader/Start               |                       |                  | System.Xml, Culture=neutral, PublicKeyToken=null |                                                                  |                                                                             
Microsoft-Windows-DotNETRuntime/AssemblyLoader/KnownPathProbed     |                       |      0           |                                                  |                                                                  | FilePath="D:\dotnet-test\shared\Microsoft.NETCore.App\3.0.0\System.Xml.dll" 
Microsoft-Windows-DotNETRuntime/AssemblyLoader/ResolutionAttempted |     FindInLoadContext | AssemblyNotFound | System.Xml, Culture=neutral, PublicKeyToken=null |                                                                  |                                                                             
Microsoft-Windows-DotNETRuntime/AssemblyLoader/ResolutionAttempted | ApplicationAssemblies | Success          | System.Xml, Culture=neutral, PublicKeyToken=null | D:\dotnet-test\shared\Microsoft.NETCore.App\3.0.0\System.Xml.dll |                                                                             
Microsoft-Windows-DotNETRuntime/AssemblyLoader/Stop                |                       |                  | System.Xml, Culture=neutral, PublicKeyToken=null | D:\dotnet-test\shared\Microsoft.NETCore.App\3.0.0\System.Xml.dll |

**Comment by brianrob** [comment]
Thanks much!  LGTM.

**Comment by elinor-fung** [comment]
cc @lpereira @vitek-karas

**Pull request merged**
