### PR TITLE
Revert "Introduce compiled shared instances of commonly used regex"

### PR DESCRIPTION
**Pull request by brianrob**
This reverts commit f4b3490205e060ed1a4de4daf95f049962caecf9.

### CODE REVIEW

**Comment by brianrob** [comment]
@phduck, there is something about your change that the CI doesn't like, and so it's been failing since I merged your change.  Interestingly though, the CI run for #1144 succeeded, so I can't explain that.  I'm going to revert this for now, and then try and figure out what happened.

**Comment by PhDuck** [comment]
Sure. 

I don't really see why it should fail tho'. Does the CI give any information about what it is failing on?

**Comment by sharwell** [comment]
super strange...

**Comment by brianrob** [comment]
It's very weird - it fails to nuget restore PerfView.sln and says it's malformed.  I would not have believed that your change would touch this, but it seems to have some impact.  I very much can't explain it.

**Pull request merged**
