### PR TITLE
Change AddDispatch Hook to allow wrapping hooks

### PR DESCRIPTION
**Pull request by vancem**
Jeff checked in AddDispatch but after the review I wanted the API to easily support 'wrapping' (e.g. lock) scenarios.
(That is the hook is called which can set somethign up, call the original dispatch, and then tear it down).
I talked with Jeff, and I he is OK with this change.

### CODE REVIEW

**Comment by vancem** [comment]
@jeffschwMSFT  please let me know if you like this or not.

**Comment by jeffschwMSFT** [comment]
LGTM.  Thanks @vancem

**Comment by sharwell** [comment]
@vancem It looks like the test failure in this pull request is a true failure.
https://ci.appveyor.com/project/sharwell/perfview/build/1.0.664/job/phemuumu2ngch59n/tests

**Comment by vancem** [comment]
Fix in #510

**Pull request merged**
