### PR TITLE
Support ubuntu 22.04 in perfcollect

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes https://github.com/microsoft/perfview/issues/1850

### CODE REVIEW

**Review by brianrob — APPROVED** [review]

**Comment by cincuranet** [comment]
@brianrob I think we discussed this before. We didn't want to implicitly install `liblttng-ust1` because the user-space tracing is not going to work because of runtime incompatibility with ABI changes in LTTng. 

Is runtime side fixed now?

**Comment by brianrob** [comment]
@cincuranet this sounds familiar now that you mention it - I was thinking that it was still useful to install because we can get kernel events, but I wasn't thinking because `lttng-ust` isn't used for kernel events.

I do worry a bit about installing this and then not having things work.  I don't think that this is fixed, as I don't think there are any plans to fix it.  I wonder if we should just avoid install `lttng-ust` on newer distros and just have `perfcollect` print a warning.  What do you think?

**Comment by cincuranet** [comment]
I think we can look at it from two angles.

1. You know the story about `lttng-ust` and you're aware of the consequences and you simply want to conveniently install all that needs to be installed and do whatever you're trying to do.
2. You don't know about the ins and outs. The warning/error is probably a good idea to prevent unexpected surprises.

Not sure which of the two is more common. 

Now as I'm writing this, what about printing warning and then either asking whether to continue or relying on `force` (either reusing the existing one or having separate) switch to either stop (when not present) or continue (when present)?

**Comment by brianrob** [comment]
@cincuranet, I like your idea about warning the user.  I think we should do that, but rather than prompting, let's just say "use -f to force installation".  And then, we will need to make sure that the collect code works properly so that it continues to work even if lttng isn't installed (it just skips that part).  I think this just means that we need to detect and set `$useLttng=0`.

**Comment by brianrob** [comment]
FWIW, someone just reported this exact issue.  LTTng installed, but they never get any events because it's version 2.13.x.

**Comment by cincuranet** [comment]
@brianrob, OK, I'll take it from here and prepare PR.

**Pull request merged**
