### PR TITLE
Fix CtfChannel Improper Read Behavior

### PR DESCRIPTION
**Pull request by cincuranet**
Various places ignored when `Stream.Read` would read less on first try, and would read more on next attempt (as standard `Stream` behavior).

### CODE REVIEW

**Comment by cincuranet** [comment]
@brianrob With this fix, all the "missing events" issues we discussed are gone.

**Review by LoopedBard3 — APPROVED** [review]
LGTM!

**Comment by cincuranet** [comment]
@brianrob Any ETA when version with this will be published on NuGet (package `Microsoft.Diagnostics.Tracing.TraceEvent`)?

**Comment by brianrob** [comment]
I am in the process of going through the backlog of PRs from last month while I was out.  Once that's done, I'll plan to create a new release.  Expect this to be in ~1 week.

**Comment by cincuranet** [comment]
Awesome. Thanks.

**Pull request merged**
