### PR TITLE
Add a command-line option to RunCommandDialog.

### PR DESCRIPTION
**Pull request by paulomorgado**
Addresses #1364

### CODE REVIEW

**Comment by brianrob** [comment]
@paulomorgado, overall, I think this looks good.  One thing: Can you add "PerfView.exe" to the beginning of the command line.  Right now, the value that gets copied to the clipboard doesn't include the executable.

**Comment by paulomorgado** [comment]
That's on purpose.

What should we do?
* Add the full path to the current executable (**PerfView** vs. **PerfView64**)?
* Add just the file name of the current executable (**PerfView** vs. **PerfView64**)?
* Add the **.exe** extension? Or not?
* If the user is in the same path as the **PerfView** executable on a **PowerShell** prompt, not prefixing with **.\** will fail to find **PerfView**.

**Comment by brianrob** [comment]
I would say that it's fine to just stick PerfView.exe at the beginning and call it a day.

**Comment by paulomorgado** [comment]
Done!

**Review by brianrob — APPROVED** [review]

**Pull request merged**
