### PR TITLE
Add support to parse SYSTEMTIME type

### PR DESCRIPTION
**Pull request by xleza**
Currently the DynamicTraceEventParser parses SYSTEMTIME in a wrong way, because it treats SYSTEMTIME as a FILETIME that causes this problem. I added support to parse the SYSTEMTIME in a correct way.

### CODE REVIEW

**Comment by xleza** [comment]
Currently the DynamicTraceEventParser parses SYSTEMTIME in a wrong way, because it treats SYSTEMTIME as a FILETIME that causes this problem. I added support to parse the SYSTEMTIME in a correct way.

**Comment by brianrob** [comment]
@xleza this change seems pretty reasonable to me.  Would you be able to capture a small trace that contains a SYSTEMTIME argument that you can add to the test bed here so that we don't break this in the future?

**Comment by gelasultana** [comment]
@brianrob Added .etl file which contains primitives in order to check how does the DynamicTraceEventParser parses them. So SYSTEMTIME parsing is fully covered.

**Comment by brianrob** [comment]
Thanks @gelasultana!

**Review by brianrob — APPROVED** [review]

**Pull request merged**
