### PR TITLE
3 UI changes to the Events view

### PR DESCRIPTION
**Pull request by Maoni0**
1) increasing the columns displayed in the Events view to 10 before resolving to Rest.for someone who uses the Events view heavily only displaying 4 columns before resolving to Rest seems like a unnecessary limitation (was this because this was written at a time when we had very small monitors? 😄). 

2) displaying the Events view window maximized by default because most likely you will want to do that

3) changed the Rest column to fit the window instead of leaving a huge amount of space which means if you select that column you will mostly see just empty space and just lost most of your valuable columns on the left hand side - 

image

### CODE REVIEW

**Comment by brianrob** [comment]
Thanks @Maoni0, these are great changes.  Overall, the code looks reasonable.  The one thing that I noticed during testing is that the horizontal scrollbar doesn't appear even if there is enough contents to warrant one.  This means that you can't scroll to the right to see the rest of the `Rest` column.  Can you take a look and see if you can fix this?

**Comment by Maoni0** [comment]
right, I noticed that too. I just copy the cell and see the data that way. but it's completely rare that I do that because when the cell gets very long, I always resort to multiple columns (it seems quite inconvenient to read such a long line anyway IMO). I have no idea how to make the scroll bar appear due to my extremely limited WPF knowledge 😆 so I'm happy to leave that change out if you like.

**Comment by brianrob** [comment]
Fair enough.  Let's leave that one out so that folks don't trip over it.  I have no idea how to fix it either.  :)

**Comment by Maoni0** [comment]
done :)

**Review by brianrob — APPROVED** [review]
LGTM.  Thanks!

**Pull request merged**
