### PR TITLE
Add updated tests data and remove DebugListenerBlock

### PR DESCRIPTION
**Pull request by nategraf**
This PR removes the DebugListenerBlock and adds updated test data to eliminate asserts on donetcore 2.0 EventPipe generated data so that asserts will not fire on load

Related: #387

### CODE REVIEW

**Comment by nategraf** [comment]
@vancem The test for v1 EventPipe objects currently fails because it uses data without the write size fix. Is the best solution to cobble together a v1 object codebase with the size fix cherry-picked in and submit that as the new test data?

**Comment by vancem** [comment]
> The test for v1 EventPipe objects currently fails because it uses data without the write size fix. Is the best solution to cobble together a v1 object codebase with the size fix cherry-picked in and submit that as the new test data?

No.   For better or worse, the V1 format has effectively shipped in .NET Core, and we can't change it.   The current test file accurately represents what a 2.0 .NET Core runtime will produce it is correct the way it is.

What this means is that we can't eliminate the DebugListenerBlock completely.  But we should only have it when running V1 format tests.  We probably should create a separate test for the V1 format (Don't lump it in with the others).  and when we don't care about the V1 format anymore we can eliminate it (and DebugListenerBlock), as a test case.

**Comment by nategraf** [comment]
The fix to the payload sizes doesn’t effect the format of the data (or the ability of PerfView to read the files); it prevents extra empty/garbage bits from being written which TraceEvent correctly ignored, except in the DebugValidate function. The v1 test data with the fix (which was easier to generate than I originally thought) still verifies the ability of PerfView to read data from Core CLR that does not contain the fix, but it will not trigger asserts. In this sense I think we should use the new data because it still follows the v1 format, and will not degrade the value of the test, but it will allow us to fully eliminate the DebugListenerBlock (instead of creating a special case)

**Comment by vancem** [comment]
LGTM

**Pull request merged**
